#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
/*
 * generated by Xtext 2.11.0.RC2
 */
package ${basePackage}.ide


/**
 * Use this class to register ide components.
 */
class ${dslName}IdeModule extends Abstract${dslName}IdeModule {
}
