#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
/*
 * generated by Xtext
 */
package ${basePackage}.ui.contentassist

import ${basePackage}.ui.contentassist.Abstract${dslName}ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html${symbol_pound}contentAssist on how to customize content assistant
 */
class ${dslName}ProposalProvider extends Abstract${dslName}ProposalProvider {
}
