#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
/*
 * generated by Xtext 2.11.0.RC2
 */
package ${basePackage}


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ${dslName}StandaloneSetup extends ${dslName}StandaloneSetupGenerated {

	def static void doSetup() {
		new ${dslName}StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
