#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
/*
* generated by Xtext
*/
package ${basePackage};

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ${dslName}StandaloneSetup extends ${dslName}StandaloneSetupGenerated{

	public static void doSetup() {
		new ${dslName}StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

