#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
/*
 * generated by Xtext
 */
package ${basePackage};

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ${dslName}RuntimeModule extends ${basePackage}.Abstract${dslName}RuntimeModule {

}
