#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
/*
 * generated by Xtext 2.11.0.RC2
 */
package ${basePackage}


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ${dslName}RuntimeModule extends Abstract${dslName}RuntimeModule {
}
